{
 "title": "Mirakurun",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Mirakurun Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mirakurun_memory_usage_bytes{label=\"heapTotal\"}",
     "legendFormat": "heapTotal"
    },
    {
     "expr": "mirakurun_memory_usage_bytes{label=\"heapUsed\"}",
     "legendFormat": "heapUsed"
    },
    {
     "expr": "mirakurun_memory_usage_bytes{label=\"rss\"}",
     "legendFormat": "rss"
    }
   ]
  },
  {
   "title": "Mirakurun Programs DB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mirakurun_programs_db_events{label=\"storedEvents\"}",
     "legendFormat": "stored events"
    }
   ]
  },
  {
   "title": "Mirakurun Stream",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mirakurun_stream_count{label=\"decoder\"}",
     "legendFormat": "decoder"
    },
    {
     "expr": "mirakurun_stream_count{label=\"tsFilter\"}",
     "legendFormat": "TSFilter"
    },
    {
     "expr": "mirakurun_stream_count{label=\"tunerDevice\"}",
     "legendFormat": "TunerDevice"
    }
   ]
  },
  {
   "title": "Mirakurun Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mirakurun_error_count{label=\"uncaughtException\"}",
     "legendFormat": "uncaught exception"
    },
    {
     "expr": "mirakurun_error_count{label=\"tunerDeviceRespawn\"}",
     "legendFormat": "tuner device respawn"
    },
    {
     "expr": "mirakurun_error_count{label=\"bufferOverflow\"}",
     "legendFormat": "buffer overflow"
    }
   ]
  },
  {
   "title": "Mirakurun Timer Accuracy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mirakurun_timer_accuracy{label=\"m1avg\"}",
     "legendFormat": "avg m1"
    },
    {
     "expr": "mirakurun_timer_accuracy{label=\"m5avg\"}",
     "legendFormat": "avg m5"
    },
    {
     "expr": "mirakurun_timer_accuracy{label=\"m15avg\"}",
     "legendFormat": "avg m15"
    }
   ]
  }
 ]
}