{
 "title": "TV Recording",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Host CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Host Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Buffers" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "Cached" }
   ]
  },
  {
   "title": "Host I/O Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[1m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Record Channel Cnt [ time ]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(VIEW.time,$__interval),\n  VIEW.name AS metric,\n  VIEW.cnt\nFROM (\nSELECT truncate(Recorded.endAt/1000,0) AS time,Services.name,1 AS cnt FROM Recorded INNER JOIN Services ON Recorded.channelId=Services.id WHERE Recorded.endAt IS NOT NULL \nUNION ALL\nSELECT truncate(Recorded.startAt/1000,0) AS time,Services.name,0 AS cnt FROM Recorded INNER JOIN Services ON Recorded.channelId=Services.id WHERE Recorded.endAt IS NOT NULL \n) AS VIEW\nWHERE\n  $__unixEpochFilter(VIEW.time)\nGROUP BY 1,2\nORDER BY $__unixEpochGroup(VIEW.time,$__interval)"
    }
   ]
  },
  {
   "title": "Record Channel Cnt [ total ]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(VIEW.endAt,$__interval),\n  VIEW.name AS metric,\n  COUNT(VIEW.name) AS \"cnt\"\nFROM (SELECT truncate(Recorded.endAt/1000,0) AS endAt,Services.name FROM Recorded INNER JOIN Services ON Recorded.channelId=Services.id WHERE Recorded.endAt IS NOT NULL) AS VIEW\nWHERE\n  $__unixEpochFilter(VIEW.endAt)\nGROUP BY 1,2\nORDER BY $__unixEpochGroup(VIEW.endAt,$__interval)"
    }
   ]
  },
  {
   "title": "Drop Cnt [ time ]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(VIEW.time,$__interval),\n  VIEW.name AS metric,\n  VIEW.cnt\nFROM (\nSELECT truncate(Recorded.endAt/1000,0) AS time,Services.name, Recorded.dropCnt AS cnt FROM Recorded INNER JOIN Services ON Recorded.channelId=Services.id WHERE Recorded.endAt IS NOT NULL \nUNION ALL\nSELECT truncate(Recorded.startAt/1000,0) AS time,Services.name,0 AS cnt FROM Recorded INNER JOIN Services ON Recorded.channelId=Services.id WHERE Recorded.endAt IS NOT NULL \n) AS VIEW\nWHERE\n  $__unixEpochFilter(VIEW.time)\nGROUP BY 1,2\nORDER BY $__unixEpochGroup(VIEW.time,$__interval)"
    }
   ]
  },
  {
   "title": "Drop Cnt [ Total ]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(VIEW.endAt,$__interval),\n  VIEW.name AS metric,\n  SUM(VIEW.dropCnt) AS \"cnt\"\nFROM (SELECT truncate(Recorded.endAt/1000,0) AS endAt,Services.name, Recorded.dropCnt FROM Recorded INNER JOIN Services ON Recorded.channelId=Services.id WHERE Recorded.endAt IS NOT NULL) AS VIEW\nWHERE\n  $__unixEpochFilter(VIEW.endAt)\nGROUP BY 1,2\nORDER BY $__unixEpochGroup(VIEW.endAt,$__interval)"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image!=\"\",container_label_org_label_schema_group=\"\",name=~\"epgstation|epgstation-mysql|mirakc\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\",container_label_org_label_schema_group=\"\",name=~\"epgstation|epgstation-mysql|mirakc\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Cached Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (container_memory_cache{image!=\"\",container_label_org_label_schema_group=\"\",name=~\"epgstation|epgstation-mysql|mirakc\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image!=\"\",container_label_org_label_schema_group=\"\",name=~\"epgstation|epgstation-mysql|mirakc\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\",container_label_org_label_schema_group=\"\",name=~\"epgstation|epgstation-mysql|mirakc\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}